[versions]
kotlin = "1.7.20"
tgbotapi = "4.2.4-branch_4.2.4-build1324"
ktor = "2.2.1"
kotlin-process = "1.4.1"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }

tgbotapi-behaviour-fsm = { module = "dev.inmo:tgbotapi.behaviour_builder.fsm", version.ref = "tgbotapi" }
tgbotapi-api = { module = "dev.inmo:tgbotapi.api", version.ref = "tgbotapi" }

ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }

kotlin-process = { module = "com.github.pgreze:kotlin-process", version.ref = "kotlin-process" }
